flowchart LR
    NUCLEO[NUCLEO-G431RB\nSTM32G431RB] -->|PA12 FDCAN1_TX| CAN_TXD[SN65HVD230 TXD]
    CAN_RXD[SN65HVD230 RXD] -->|PA11 FDCAN1_RX| NUCLEO
    NUCLEO -->|3.3V| CAN_VCC[SN65HVD230 VCC]
    NUCLEO -->|GND| CAN_GND[SN65HVD230 GND]

    CAN_TRANS[SN65HVD230 CAN Transceiver] -->|CANH| WAVESHARE[Waveshare USB-CAN]
    CAN_TRANS -->|CANL| WAVESHARE
    CAN_GND -->|Common GND| WAVESHARE

    NUCLEO -->|5V| MAXVCC[MAX7219 VCC]
    NUCLEO -->|GND| MAXGND[MAX7219 GND]
    NUCLEO -->|PB6 / D10| MAXDIN[MAX7219 DIN]
    NUCLEO -->|PB7| MAXCLK[MAX7219 CLK]
    NUCLEO -->|PB8 / D15| MAXCS[MAX7219 CS/LOAD]

    MAX7219[MAX7219 4-Module LED Matrix]
    MAXVCC --> MAX7219
    MAXGND --> MAX7219
    MAXDIN --> MAX7219
    MAXCLK --> MAX7219
    MAXCS --> MAX7219
